micronaut:
  application:
    name: pokemon-card-service
  server:
    port: 8080

mongodb:
  uri: mongodb://localhost:27017/pokemon_db

app:
  seed-data: true
  verify-indexes: true
  init-db: true

logger:
  levels:
    com.example: INFO
    root: INFO
